[[constraint]]
  branch = "master"
  name = "code.gitea.io/git"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.7"

[[constraint]]
  branch = "master"
  name = "github.com/azer/snakecase"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[prune]
  go-tests = true
  unused-packages = true
